#
# Builds the plugin
#
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NAME: 'annotator'
  CI_STATS_DISABLED: 'true'
  DEBIAN_FRONTEND: 'noninteractive'           # Indicate headless operation

jobs:
  config:
    uses: ./.github/workflows/config.yml

  setup_kibana:
    needs: config
    uses: ./.github/workflows/kibana.yml
    with:
      stackVersion: ${{ needs.config.outputs.stackVersion }}
      stackArch: ${{ needs.config.outputs.stackArch }}

  build_plugin:
    needs: [config, setup_kibana]
    runs-on: ubuntu-latest
    env:
      ES_STACK_VERSION: ${{ needs.config.outputs.stackVersion }}

    steps:
    - name: Install packages
      run: |
        npm install -g yarn
        yarn config set network-timeout 100000 -g && npm config set legacy-peer-deps=true

    - name: Restore cache for Kibana source repository
      id: cache-kibana-repository
      uses: actions/cache@v4
      with:
        path: ${{ needs.setup_kibana.outputs.path }}
        key: ${{ needs.setup_kibana.outputs.cacheKey }}

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "yarn_dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      # ~1 GB
    - name: Restore yarn cache
      uses: actions/cache@v4
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.yarn_dir }}
        key: ${{ runner.os }}-yarn-kibana-${{ env.ES_STACK_VERSION }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-kibana-${{ env.ES_STACK_VERSION }}

    - name: Checkout
      uses: actions/checkout@v5
      with:
        path: plugin

    - name: Move repo
      run: mv ${GITHUB_WORKSPACE}/plugin ${{ needs.setup_kibana.outputs.path }}/plugins/${{ env.NAME }}

    - name: Bootstrap plugin
      run: |
        source "${HOME}/.nvm/nvm.sh"
        cd ${{ needs.setup_kibana.outputs.path }}/plugins/${{ env.NAME }}
        nvm install && nvm use
        yarn kbn bootstrap

    - name: Lint
      run: |
        source "${HOME}/.nvm/nvm.sh"
        cd ${{ needs.setup_kibana.outputs.path }}/plugins/${{ env.NAME }}
        nvm install && nvm use
        node ../../scripts/eslint .

    - name: Build plugin
      run: |
        source "${HOME}/.nvm/nvm.sh"
        cd ${{ needs.setup_kibana.outputs.path }}/plugins/${{ env.NAME }}
        nvm install && nvm use
        yarn build --kibana-version "${{ env.ES_STACK_VERSION }}"

    - name: Generate coverage report
      run: |
        source "${HOME}/.nvm/nvm.sh"
        cd ${{ needs.setup_kibana.outputs.path }}/plugins/${{ env.NAME }}
        nvm install && nvm use
        yarn test:coverage

    - name: Upload artefacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.NAME }}-plugin-${{ env.ES_STACK_VERSION }}
        path: ${{ needs.setup_kibana.outputs.path }}/plugins/${{ env.NAME }}/build/*.zip
        compression-level: 0
